### PR TITLE
Attach toolbar to bottom of viewport on mobile

### PR DESCRIPTION
**Pull request by seaneking**
The mobile toolbar should actually be visible whenever simpla-text is focussed, not just when a range is selected. But didn't even know where to start with that one...

### CODE REVIEW

**Comment by bedeoverend** [comment]
Yeah that's probably something for me to do w/ prosemirror.

This looks pretty nasty on my phone:



HTML Source to replicate:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <script src="/components/webcomponentsjs/webcomponents-lite.min.js"></script>
    <script src="/components/simpla/simpla.js"></script>
    <script>
      Simpla.init('local');
    </script>
    <link rel="import" href="/components/simpla-text/simpla-text.html">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <title></title>
    <style media="screen">
      body {
        padding: 50px;
      }
    </style>
  </head>
  <body>
    <simpla-text id="main" path="/text-0" editable>Hello World</simpla-text>
  </body>
</html>
```

That's iOS Safari, can debug in regular Safari by just changing it to send an iPhone User Agent, gives the same result.

**Comment by seaneking** [comment]
Okay, must not be bailing on abspos logic properly. Could you skim through this PR and see where it might be going wrong? If mobile is true the toolbar shouldn't be positioned at all with JS.

**Comment by bedeoverend** [comment]
Ah yeah so it looks like hoverOverRange might get called before the toolbar is actually attached to the DOM. Probably worth only having it hover over the range _after_ attached, buuut for now do you just want to change this PR to compute the mobile value as a global constant? e.g. something like this

```js
let detect = new MobileDetect(window.navigator.userAgent);
const IS_MOBILE = !!(detect.mobile() || detect.tablet());

class SimplaTextToolbar {
  hoverOverRange(range) {
    let rangeBounds,
         ownBounds,
         boundaries,
         left,
         top;
            
    this.hidden = !range;
    
    if (!range || IS_MOBILE) {
      return;
    }
    
    ...
  }
}
```

**Comment by seaneking** [comment]
Would chucking it in `created` work? Just kinda messy, because you'd still have to set it to a prop for the reflected attribute.

**Comment by bedeoverend** [comment]
Oh well I'd just set value when you set on properties:

```js
properties: {
  mobile: {
    type: Boolean,
    value: IS_MOBILE,
    reflectToAttribute: true
  }
}
```

**Comment by bedeoverend** [comment]
I meant, the fact that they're on a mobile isn't going to change between instances or over time

**Comment by seaneking** [comment]
No, it's just got a bad code smell

```
mobile: {
  value:  IS_MOBILE

**Comment by bedeoverend** [comment]
Oh yeah sure use a prop. All I'm saying, is that the value of whether it's mobile or not (either in a prop or a constant) needs to be set as early as possible

**Comment by seaneking** [comment]
Oh okay gotcha. I'm hazy on Polymer lifecycle, so setting `value` of the prop will definitely happen before `hoverOverRange` could ever be called?

**Comment by bedeoverend** [comment]
Yeah - the `beforeRegister` kinda happens before the `constructor` (it's confusing thanks to ES6 classes being used in Polymer 1.x). But essentially that's the earliest things can happen. In v1 API you'd just do it in the constructor.

**Comment by seaneking** [comment]
Travis is erroring in a pretty spectacular fashion all of a sudden - any idea why?

**Comment by bedeoverend** [comment]
Lordy. Yeah I'll have a squiz and patch it up. Once they're fixed you're happy for me to merge?

**Comment by seaneking** [comment]
👍

**Comment by bedeoverend** [comment]
@seaneking see last commit heh 😉 we need to add linting to our tests me thinks

**Pull request merged**
